### ISSUE TITLE
Create Marketing Qualified Detail and Fix Historic data

### ISSUE THREAD

**Issue by nicholassewitz** [artsy/clouds#10]
@nicholassewitz to create new field in Salesforce to split out Marketing Qualified Reason Filled Out Form and the Form Detail
- also fix historic data

@cfinsness to fix process to take into account new structure.

**Comment by nicholassewitz** [comment]
@cfinsness I created field on lead/contact so you can fix process.

Still need to create on patron and fix APEX to update

**Comment by cfinsness** [comment]
@nicholassewitz process is fixed now (https://app-ab14.marketo.com/#SC2752C3)

**Comment by nicholassewitz** [comment]
Have updated historical information Closing our first Issue!!!!!
