### ISSUE TITLE
Deprecate Old Lifecycle Stage Field

### ISSUE THREAD

**Issue by nicholassewitz** [artsy/clouds#102]
I was thinking of going through all of these smart campaigns and removing reference to the old Lifecycle Stage field in Marketo. Do you know if we actually use it for anything? It's very confusing.

https://cl.ly/0C3B2P0r0P1s

https://app-ab14.marketo.com/#FM0A1

**Comment by cfinsness** [comment]
yeah i referenced this field on this ticket https://github.com/artsy/clouds/issues/16 as a to do
