### ISSUE TITLE
Blank MQL Reasons

### ISSUE THREAD

**Issue by cfinsness** [artsy/clouds#104]
https://artsy.my.salesforce.com/00OC0000006brnc

**Comment by cfinsness** [comment]
Not sure what happened but seems to have something to do with the duplicate clean up 

e.g. https://artsy.my.salesforce.com/003C00000298Uff?srPos=0&srKp=003 
was stamped MQL w.o a reason on Sept 8 exactly when cleanup happened
<img width="945" alt="screen shot 2017-09-18 at 12 46 41 pm" src="https://user-images.githubusercontent.com/6314270/30553532-7cb53300-9c6f-11e7-81cd-49fc7b3a6fea.png"> @nicholassewitz

**Comment by nicholassewitz** [comment]
hmm there are only 11 of them and they are all contacts it looks like they were created with mql date. I can delete
