### ISSUE TITLE
Restructure Application Flow by Company Type

### ISSUE THREAD

**Issue by cfinsness** [artsy/clouds#11]
Restructure flow in Marketo so that the appropriate team receives the application by company type selected.

**Comment by cfinsness** [comment]
Here’s the draft of the new application flow to review @nicholassewitz 

1. [Capture all applications ](https://app-ab14.marketo.com/#SC3726A1)
2. [Juncture by company type ](https://app-ab14.marketo.com/#SC3727A1)
Prioritizing Partner Type fields first, then Type on lead level, then by what type of form they filled out if for whatever reason org type was not captured. 

3. a. [Process galleries ](https://app-ab14.marketo.com/#SC3727A1)
b. [Process Auctions, Institutions, Fairs](https://app-ab14.marketo.com/#SC3732A1)
d. [Process Artists and Other ](https://app-ab14.marketo.com/#SC3730A1)

The email copy for auto-responses is still on it’s way (related to [issue #12](https://github.com/artsy/clouds/issues/12))

**Comment by nicholassewitz** [comment]
We looked over and !!!!! good job. Now lets see it in action

**Comment by nicholassewitz** [comment]
looks like there are a few problems. 

- This [lead](https://artsy.lightning.force.com/one/one.app#/sObject/00QC000001jO3ImMAK/view) applied without a website.
@cfinsness

**Comment by cfinsness** [comment]
@nicholassewitz the new page isn't live yet, so we haven't activated this flow. 

Also the link in your last comment doesn't work - record was deleted?

**Comment by nicholassewitz** [comment]
ahh shoot ya he was deleted. must have been spam

**Comment by cfinsness** [comment]
just made new flow live 
=^.^=
