### ISSUE TITLE
Automatic responses to application submissions

### ISSUE THREAD

**Issue by cfinsness** [artsy/clouds#12]
**Step 1**
- [x] Create message to non-applicable partner types (artists, other)
- [x] Adjust language for auto responses to galleries for complete applications
- [x] Adjust language for auto responses to galleries for incomplete applications

**Step 2** 

Create response for complete and incomplete applications for 
- [x] Auctions
- [x] Fairs
- [x] Institutions

Current copy available [here](https://docs.google.com/document/d/1tRHGyHZh7enS1O-Lkt2GNjh8zCBfy03wAxBgQ4nSMuY/edit)

**Comment by nicholassewitz** [comment]
love the structure of this issue

**Comment by nicholassewitz** [comment]
@mdole can we close this issue?

**Comment by mdole** [comment]
@nicholassewitz should be able to later today. just sending a final test to institutions now and I'll close it afterwards
