### ISSUE TITLE
Trigger Reassignment for Existing Contact Failed

### ISSUE THREAD

**Issue by nicholassewitz** [artsy/clouds#15]
This contact in SF [salesforce](https://artsy.my.salesforce.com/003C000001iOcb5)[marketo](https://app-ab14.marketo.com/access/leadDetail?sfdcContactId=003C000001iOcb5IAC&tok=xVoNJZWbUlUb7xYguq3Bcfih3SbGfpuLtLJpCPTy%2B8t8gwouIr%2FsaBG%2F2IMAFb0xZ7y3ICFSX9JywQBdCdWGeZJp%2FrcHSRHiDRiv0PGKP91vIJZQ0OhA0erpmmMXr9mHnEjFCENMGjNqZzSYebAykAvuNYdhE0GS6X7THINhxmoPkLgXwrKqb6f6%2BHyttwiE4TqKIV14ppvZ50%2B1TtUons8RtlMh%2BxJ8LLWms2yXleh0%2FDs%3D) applied via the inbound application flow. The trigger reassignment for existing contacts was called but the the flow step to reassign seems to have been skipped because it was member of a smart campaign. However, the smart campaign is stale I believe.

https://cl.ly/0X0S290z302c

https://app-ab14.marketo.com/#SC2086C3

**Comment by cfinsness** [comment]
This lead is not part of either smart campaigns in the first logic step, so should have qualified for the reassignment rule. The campaign was edited on Friday so maybe it affected this lead. Let's keep an eye on it.

This brings up another point though, which is if we do create automated follow up emails encouraging the lead to apply, what is the expiration date allowing them to be reassigned to someone else (not a GPA)? @nicholassewitz 30 days?

**Comment by nicholassewitz** [comment]
I would say 14 days.

**Comment by nicholassewitz** [comment]
@cfinsness want to see if if we set the expiration to 14 days so we can close this issue.

**Comment by cfinsness** [comment]
Created rule to 'hold reassignment' for 14 days if being sent automated emails - https://app-ab14.marketo.com/#SC3482C3
Which suppresses them from being reassigned if they apply / reach threshold here - https://app-ab14.marketo.com/#SC2086C3
