### ISSUE TITLE
Fix Last Activity by GP formula

### ISSUE THREAD

**Issue by cfinsness** [artsy/clouds#24]
`Last Activity by GP` on the Lead/ Contact does not always reflect the last sales activity. We depend on this date for the Patron View (to mark a lead as Priority)

example: https://artsy.my.salesforce.com/003C0000022JCuk

**Comment by nicholassewitz** [comment]
still looking into this. can't figure out why it won't work on some

**Comment by nicholassewitz** [comment]
fixed
