### ISSUE TITLE
Limiting permissions on updating lifecycle

### ISSUE THREAD

**Issue by cfinsness** [artsy/clouds#85]
Is there a way to limit GPs so they can only update to stages to:
- Sales Accepted
- Sales Qualified
- Recycled
- Disqualified

We've seen this cause issues such as people updating lifecycle to the wrong stages by accident 

e.g. https://artsy.my.salesforce.com/003C0000024XYfg was updated to Won when the gallery was actually inactive. Even if it WAS active, a person should only have Lifecycle stage of Won if they were actually involved in closing the opp. Otherwise this inflates our conversion numbers.

**Comment by cfinsness** [comment]
@nicholassewitz

**Comment by nicholassewitz** [comment]
The one issue I see here is that sometimes Marketo will not move the person to in open opportunity when they are added to an opp. The GPM then has to do manually. I'm going to allow them to move them to In Open Opp as well as Not in Model. I added to technical documentation also.

https://artsy.my.salesforce.com/03dC00000006vRv?setupid=ContactValidations
https://artsy.my.salesforce.com/03dC00000006vRq?setupid=LeadValidations
