### ISSUE TITLE
Patron Feedback: "Already speaking to someone else at gallery"

### ISSUE THREAD

**Issue by cfinsness** [artsy/clouds#86]
Seems like the best approach is to suppress a lead from reaching behavioral threshold if there's been gp activity on the lead/account in the last x(90?) days. 

How much this would affect current queue (leads that reached threshold in August would have been excluded based on prior activity on account.) 
AUG:
90 days: - 54/ 424 (~13%)
40 days: 25/424 (~6)

SEPT:
90 days: 18/ 132 (~14%)
40 days: 6/132 (~5%)

@nicholassewitz if you have thoughts.

**Comment by nicholassewitz** [comment]
I like this idea, I think we should do less time. Maybe 45 days?

**Comment by cfinsness** [comment]
Did it based on 45 days which should take away around 5% of threshold leads per month. 
https://app-ab14.marketo.com/#SC3708B2
