### ISSUE TITLE
Remove Tier 5's that are blacklisted and No Longer in Business

### ISSUE THREAD

**Issue by nicholassewitz** [artsy/clouds#98]
Maybe add to process builder?

**Comment by cfinsness** [comment]
@nicholassewitz In this case seems good to keep the dates! 

We should make a trigger going forward that if the account = blacklist, disqualify all leads under it. Do you think we need do the same thing for Tier 5 going forward? This would be another exception to the rule where lifecycle is based on individual, but we can do that if sales would never want to talk to anyone else under that account.

**Comment by nicholassewitz** [comment]
I have made a process builder that updates on tier 5 blackisted and
permanently closed. It disqualifies all the contacts and updates the
disqualified reason.

**Comment by cfinsness** [comment]
perf
