### ISSUE TITLE
Add uncontacted SALs into Patron Views

### ISSUE THREAD

**Issue by cfinsness** [artsy/clouds#99]
**List of priority contacts**

@nicholassewitz please take a look at who shows up now based on update  https://artsy.my.salesforce.com/00OC0000006q6vO
- This limits SALES ACCEPTED contacts from showing up if they've had activity on the account level in past 45 days 
- Regardless of activity, SALES ACCEPTED LEADS will still show up cause they should prob be converted 
- If they are in MQL stage, however we are NOT limiting based on account activity through the patron logic, but rather by suppressing them from reaching threshold going forward. (will set aside time to talk about a bit more since i have q's around this). 

**Priority logic**
for contacts - https://artsy.my.salesforce.com/00NC0000006uUcm?setupid=ContactFields
for leads - https://artsy.my.salesforce.com/00NC0000006uUch?setupid=LeadFields 
will create lookup on patron to reference instead.

**Comment by nicholassewitz** [comment]
wow really clean work here cat. very impressed with the how you set up the formulas. i got them in seconds. looks good to me.

**Comment by cfinsness** [comment]
@nicholassewitz what i mean by that is here: https://app-ab14.marketo.com/#SC3708B2 
rather than adding this into the logic and removing existing mqls, we just make sure there aren't any NEW threshold MQLs if recent account activity
